version: 0.2

env:
  variables:
    OUTPUT_DIR: "output"

phases:
  build:
    commands:
      - echo "Creating output directory..."
      - mkdir -p $OUTPUT_DIR
      - echo "Fetching Security Hub CIS 1.2 findings..."
      - aws securityhub get-findings --filters '{"StandardsArn":[{"Value":"arn:aws:securityhub:::standards/cis-aws-foundations-benchmark/v/1.2.0","Comparison":"EQUALS"}]}' --output json > "$OUTPUT_DIR/securityhub-cis-1.2.json"
      - echo "Security Hub findings saved to $OUTPUT_DIR/securityhub-cis-1.2.json"

artifacts:
  files:
    - "output/securityhub-cis-1.2.json"
