version: 0.2

env:
  variables:
    OUTPUT_DIR: "securityhub-output"
    AWS_REGION: "eu-central-1"

phases:
  install:
    commands:
      - echo "Installing jq if not present"
      - command -v jq || sudo yum install -y jq

  build:
    commands:
      - echo "Creating output directory"
      - mkdir -p "$OUTPUT_DIR"

      - echo "Fetching failed Security Hub findings"
      - FILTERS="{\"ComplianceStatus\":[{\"Value\":\"FAILED\",\"Comparison\":\"EQUALS\"}],\"ProductName\":[{\"Value\":\"Security Hub\",\"Comparison\":\"EQUALS\"}]}"
      - aws securityhub get-findings --region "$AWS_REGION" --filters "$FILTERS" --max-results 100 --output json > "$OUTPUT_DIR/all_failed_findings.json" || echo '{"Findings":[]}' > "$OUTPUT_DIR/all_failed_findings.json"

      - echo "Filtering CIS AWS Foundations Benchmark v1.2.0 findings"
      - jq '.Findings[] | select(.Compliance.AssociatedStandards? != null) | select(.Compliance.AssociatedStandards[].StandardsId == "ruleset/cis-aws-foundations-benchmark/v/1.2.0")' "$OUTPUT_DIR/all_failed_findings.json" > "$OUTPUT_DIR/cis_1_2_failed.json" || true

      - echo "CIS 1.2 findings written to $OUTPUT_DIR/cis_1_2_failed.json"

artifacts:
  files:
    - securityhub-output/cis_1_2_failed.json
